name = "BasicCraft"
author = "MisileLaboratory"
version = "1.42.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d2e3547a348777e798d77285d80f542e29cf68d6f7565ac797203602298e13c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
