hash-format = "sha256"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "80920e7f25490ed3289314a391e4c83f2f7b5630d75b49a30353eab88659466d"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "69b07ae8cb0d37e1179a76c6c182f6746e7f86978e519e74162b8e30b6791452"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "7823fc7bb5b474d3a39a2ff8e71054812499439cef63fbaa7124930de296c7cf"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "bc7cfadfe7121fdbd356c7992705ea6f484de518d3fd473eb8c59ea93e79a04d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "aa798e887fb1fe69563a06e259dc2be59bcb3baf45ec05c1ded759ac6c1ff3ef"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "ef55a85f0905e41d93de2b7e53266d393bf58f43917d9b15ea8f66b757a5996d"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "c951505f545e9d7f57ba66201609eac1792469e22fa13efcade818fc8b61cbe2"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "c668b4ad565c58243a1e0eb71884b17c77ab2242d983075f12dc2666060709ba"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/ok_zoomer/config.toml"
hash = "a7c05cd6ad8a8fcd1399b40aefe221c9cbaa67e58fac4b477bda534ec92d9ded"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "481193336b67c5a9a82beec77880556f3b92fd792cd8ea4414a904dd66acd733"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "5b24c9a57bb6092df95d9e8ec3c79574103967cef4db94508b9b172df1e447e5"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "564937e9bb15ddeb6741ce741a35486bc71b2a9a178d176b6107cfcb30747540"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "c602ad2f5d370579a6f530355b2c60852fbbbfa6c230ebb568cbf79ec290e76b"

[[files]]
file = "config/yosbr/options.txt"
hash = "a737dd82279403a1a22b4dcd1fa3f99915f4feac38879042a8b1da6a4ccac199"

[[files]]
file = "missing-mods"
hash = "feef102ea7524136b556082694fafc7608e14c90adddd9f813706a5499dd7ec8"

[[files]]
file = "mods/animatica.pw.toml"
hash = "7749a788cd34e08e2280dc5e05db1bbf375d7a184d787f682f7df19709a754e3"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "352fe01e3b8136cf2abf742ddc8e2cab45fd7f25f635df960053b8290e5dc2a4"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "284a7ccf2dc6ff43378230c252323359634f2b566212924ad0f138f4203079c6"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "efe9b34407e122ab02444ed4da6820984d2f015fbe2b64242f74bbce35f145d4"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "d8a788b59e239573694e09a72c14dff19cffdd5b85671fd6722130d7f4f0e831"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "39d2695bf316d7d48d21da0ae6b38ea3e74c47c3b07c93bbade4dd753df90321"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "6ebb236b2a46dbf564aa2760a68027703e44105ab18e77ea76c0fe2323a9bafb"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a8785544fb032c24853b8ed9bb15d65c30312f1ee5f7ada3e73a0350512702a0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "f89f5f135170f999c531451c50937db67abeb0b0ff623d030f35f509837209a4"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "982801b4473e11e6f8c5899f18a260515239dfce397c650c6920fc6ae03f6abb"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a89555e4ccf7ba3541cae70de8e1c11b007a50993f3b7ffc490932029ed8fdf5"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7a2991786a3523846ee1dcaa4c34c9f1d7a544ea4dbf252df8482b19549009b4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6d88f4cdcc5c08a06c25b83f67bd0e0896d61489ca6b5e508a30a10a00caa7f6"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "6085d2f0a5deabc026667492ac344d9b9007c80ccadb3f916fe9b0ec3037f022"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "b5c07339bc334ddfe27120580cca09d71541a2f8230251a85284807ff0688a4c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "249bfdcc14f0977e54a785a5686334b909f19c0d10dc9f15d01bfaa759fa74f2"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "d6c762a1ae9e43903416e37af42f63f1c485051b77d44c5501a2097c1149b630"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "402069ebe33a1f19e6e5c0c0235267b832ba44617f15ddbdc677faf2a2607e38"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "ced9729e413bbe2bd78889cbd3d3e93ae56b06c9728972a06ff03afe8a0f4eba"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e26dacab5ed497b7bf6500e389eba5e21cd4b9d7b38089045cd26818a4d2f589"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9c15d70a164a6e16b09212b6a24d097003f86bb595634a66c04b9a31dff38ff4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "43b7544c0a49c9368caf33a1529a720c6fadb17f7d07db6a8e952b514b5a862c"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "fa3e6df3d222c94014c840673aa92455210d404eadceb05dd5ab3ae5a3eab6db"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/nbt-autocomplete.pw.toml"
hash = "7591214280395cd292fe6c1385861c2a1d1455e89200e7f964d9aa0e4010445f"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "ebd48452773a4b6b4b7dcedbfb71c8986ec97780fcce040542c8e8fd67f22c56"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "1f9c70510fe21d5028a900ae31923e12c4bc4d7bbc38937f9c90ef75385ae6b7"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "60618900d0ec75ea05b70403860cd161c736a5cd26f533872fba13a7c7c72206"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "ee0b54d23f802ea714ecfe71c62421ca00d3b49699324bb01defab4868d529f0"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "e16d87608293bb165500f9dd290d246975286bcf41ec4bdce0e914e897c5318f"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "799419e64ed42a8175333c541a08995fc4d84a2c6000877f60262fe55892e3ff"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "50e28ae5d2bf01a1d566e8273fd5aa0a91baf22d88d981c3c1496f6513dd4687"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "a625f1f205b6d9152a66724dfc8ebe2952705daf0884e10be16c288c847346fc"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3cbdb02ff4be022d7e0f9b82cd64a36669d5986d7ed3ddcf7bcdbacc0b1b4b2a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "383d8df46529ce54b4b0574be2fd9eba4f45d8c85aa668604e152fca3e439f5a"
metafile = true

[[files]]
file = "mods/renderscale.pw.toml"
hash = "b4c4f1163795d12bb392a2645b886b6afc6e7b3e4d28af4968a6ca0c74fcb606"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "5740f9047e34375f77e59a94b5a171aa74a6f38bc4a1d4ac6583d922922a6d68"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4e4627ce19e119721a27a2ef00769d3a744f36db67d11ad3959d785462aefe1f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "dee7712131e72105b1a9dafe6e103308e33023a4a48ec3b3868298d8d6c4ed6c"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "0af1ab53ce68a6850cdd1071d3291462ea816dede99cc34e92b8a430a359b900"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "022c64cbff3fbce3b4a988405c6cb492a46592c83e842752331844de68c1d8c0"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "1435829994c9fcd11b99b0d93ea7e2f78523d3eb9071063b2052bc316e40a7c5"
metafile = true
