name = "BasicCraft"
author = "MisileLaboratory"
version = "1.40.2+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8cec8ee772250d6b258ab24b3185de5dd8c7f0bbef3d6f54c4357d3f831b8fb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
