name = "BasicCraft"
author = "MisileLaboratory"
version = "1.40.2+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6582456a7cd9fad928e59fe0c89829aebaf2a698ecd9c45c09898db40dc089d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
