name = "Additive"
author = "SkywardMC"
version = "1.39.1+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9c0bd294e34290c52480969652a8142f6390c9831013cd7f00fbd6613095f70"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
