name = "BasicCraft"
author = "MisileLaboratory"
version = "1.41.3+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2c8fdbd55f79d615e7a82e9f6ad22216f6e09b9f991923a916a1f5b37f0195b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
