name = "BasicCraft"
author = "MisileLaboratory"
version = "1.42.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5e2b92f0d6c80eda9fb4f635d107c93bde18c18ee4cb31183b4ea4ba5d4c37f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
