name = "BasicCraft"
author = "SkywardMC"
version = "1.38.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f51fca82def81b5c6c07a403078a86ce20be036909c7b4291ecc4cd0236834e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.5"
