name = "BasicCraft"
author = "MisileLaboratory"
version = "1.38.0+1.21.10.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d4ba48f36976c3b8a859db5e2fd6b8df639672c698b6f2a4e69c51fc0eed6f5"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
