name = "BasicCraft"
author = "MisileLaboratory"
version = "1.42.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd9289be916c4b3e4d31d15936732a20fefa5318d70cf1f6c2a4d60cee84365f"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
