name = "BasicCraft"
author = "MisileLaboratory"
version = "1.39.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75dedeb5b01cc15e8fb191b38e9847534281f680507cc940f30ed29745992f0f"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
